version: "3.12"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG_MODE}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL_DOCKER}
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data: